project:
  type: website

website:
  title: "Callum Webb"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



